# Generated by Django 4.0 on 2021-12-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('address_street', models.CharField(max_length=120)),
                ('address_suite', models.CharField(max_length=120)),
                ('address_city', models.CharField(max_length=120)),
                ('address_zipcode', models.CharField(max_length=120)),
                ('address_geo_lat', models.DecimalField(decimal_places=4, max_digits=15)),
                ('address_geo_lng', models.DecimalField(decimal_places=4, max_digits=15)),
                ('phone', models.CharField(max_length=120)),
                ('website', models.URLField()),
                ('company_name', models.CharField(max_length=120)),
                ('company_catchPhrase', models.TextField()),
                ('company_bs', models.CharField(max_length=1024)),
            ],
        ),
    ]
